title: 羊仔AI探索
email: your-email@example.com
description: >-
  央企程序员，AI探索者
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://z520yu.github.io" # the base hostname & protocol for your site
github_username: z520yu
author: 羊仔AI探索

# 主题设置
theme: minima

# 布局设置
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: /page:num/

# 社交链接
social:
  github: z520yu
  email: your-email@example.com

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: 文章
    url: /posts/
  - title: 分类
    url: /categories/
  - title: 标签
    url: /tags/
  - title: 关于
    url: /about/
  - title: 搜索
    url: /search/

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 