title: 我的个人博客
email: your-email@example.com
description: >-
  这是我的个人博客，在这里我会分享我的想法和经验。
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://z520yu.github.io" # the base hostname & protocol for your site
github_username: z520yu

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 